Update issue templates
QGEP/QGEP pull request #692
Opened 2021-09-24 17:26 UTC by sjib

Added new template feature request

2021-09-24 17:27 UTC, sjib commented
@ponceta I made a new template for new feature requests. Is this still in line with the template you have? Else pleaes modify,

2022-04-01 13:49 UTC, sjib commented
ping @kandre @ponceta I made a new template for new feature requests. Is this still in line with the template you have? Else pleaes modify,

2022-05-05 05:33 UTC, ponceta requested changes
Thank you Stefan, this is nice, I let you check my comments.

I let you merge this and I'll open some current feature requests as examples to check if this applies well.

2022-05-05 05:33 UTC, ponceta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +## Development and intégration
```suggestion
## Development and integration
```

2022-05-05 05:33 UTC, ponceta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +### Dates de réalisation
```suggestion
### Realisation dates
```

2022-05-05 05:33 UTC, ponceta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +### Versions of related softwares
```suggestion
### Related softwares versions
```

2022-05-05 05:33 UTC, ponceta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- Invoice date:
Not shared on Github
```suggestion
```

2022-05-05 05:33 UTC, ponceta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +- Payment date:
Not shared on Github
```suggestion
```

2022-05-05 05:33 UTC, ponceta commented on .github/ISSUE_TEMPLATE/feature_request.md
> +## Cahier des charges et offres ( Developer)
```suggestion
## Specification and offers ( Developer )
```

2022-06-22 19:49 UTC, sjib reviewed
ok now?

2022-06-22 19:51 UTC, sjib reviewed
@ponceta I have added the changes. Can you merge?

2022-06-23 08:20 UTC, ponceta commented
@sjib Seems fine to me!

2022-06-23 08:20 UTC, ponceta approved these changes

2022-06-23 08:20 UTC, merged